### ISSUE TITLE
Add a custom badge for SQLAlchemy in README's tech stack section

### ISSUE THREAD

**Issue by Aditya-Gupta1** [Aditya-Gupta1/job-application-cli#17]
Create a badge for SQLAlchemy using its logo and put it under the `Tech Stack` section.

Image: https://www.sqlalchemy.org/img/sqla_logo.png

Tools like shields.io or any other relevant tools can be used to create a custom badge (Just like already mentioned in the README)

Steps:

1. Go to https://shields.io/
2. Scroll below to the `Your Badge` Section.
![image](https://user-images.githubusercontent.com/44528202/194291452-21e9a10a-149a-4c76-8359-ef74eadd7b9f.png)
3. Leave the `label` field empty.
4. Populate the `message` as `SQLAlchemy`
5. Use the colour **blue**. 
6. Click on the `make badge` button.
7. You'll get a URL for the badge.
8. Add it to the README's tech stack section below the already existing Badges there.

**Comment by issac5693** [comment]
I wish to do this

**Comment by AnimeshKumar923** [comment]
Hello @Aditya-Gupta1 

Thank you for mentioning this issue. I would like to work on this. Please assign this to me and I'll work on it.

**Comment by Aditya-Gupta1** [comment]
> I wish to do this

Sure @issac5693. Go ahead and raise a PR for it! 👍 
(In an unlikely event if you're not able to raise a PR, please let us know so that someone else may contribute towards it.)


> Hello @Aditya-Gupta1
> 
> Thank you for mentioning this issue. I would like to work on this. Please assign this to me and I'll work on it.

Hey @AnimeshKumar923. The issues are assigned on a first come first serve basis. But don't worry, there are a lot of things to work on here and I'll let you know once other issues are ready to be worked upon. 😃

**Comment by AnimeshKumar923** [comment]
Okay. Thank you!

**Comment by issac5693** [comment]
Please assign me to the 20th(contribute.md) one, not the 17th

**Comment by Aditya-Gupta1** [comment]
I've added the steps to complete this issue @issac5693.

Issue #20 can't be assigned as of now since I'm still working on publishing this app to PyPI. Only then I will be able to lay out the steps for contribution for this repo.

Let me know if you still wish to complete #17.

**Comment by issac5693** [comment]
Thanks a lot bro, I'll complete #17
