### ISSUE TITLE
[Feature] Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by Aditya-Gupta1** [Aditya-Gupta1/job-application-cli#20]

**Comment by issac5693** [comment]
should I just add the md file will no content

**Comment by Aditya-Gupta1** [comment]
Hey @issac5693, I've assigned #17 to you. Please complete that first. Thanks 👍

**Comment by issac5693** [comment]
But how can I do that

**Comment by AdarshCoder397** [comment]
Hey @Aditya-Gupta1 , I can work on this issue!!

**Comment by manjusha2912** [comment]
Hi! I would love to work on this issue. Can you explain what the file should contain? Thanks :)

**Comment by Aditya-Gupta1** [comment]
Hey @AdarshCoder397 and @manjusha2912 👋

Great to hear you want to contribute to this project!

I'll be working on this issue and the other issues that are assigned to me.

This project is in early phases of development and will be open for a lot of contributions in a few days.

Please keep an eye out 🧐

Thanks.

**Comment by issac5693** [comment]
Completed dude
